# docker-composeのバージョン
version: '3'
# アプリケーションを動かすための要素 web db　の各要素がある
services:
  db:
    # コンテナ作成に必要なイメージを指定 
    image: postgres:11.5
    # 環境変数
    environment:
        POSTGRES_USER: 'admin'
        POSTGRES_PASSWORD: 'admin-pass'
    # 各serviceのポート番号 ホストOS(local)のポート番号:dockerコンテナ内のポート番号
    ports:
      - "3306:3306"

  web:
    # docker-compose buildのときにビルドするためのDockerfileのパス
    build: .
    # docker-compose upで実行されるコマンド
    #command: rails s -p 3000 -b '0.0.0.0'
    # webサーバー用のスクリプトを実行
    command: sh scripts/launch.sh
    # dockerの中でデータを永続化する設定 コンテナ内のデータが消えずに残る
    volumes:
      - .:/cocktailApp
      - public-data:/cocktailApp/public
      - tmp-data:/cocktailApp/tmp
      - log-data:/cocktailApp/log
    ports:
      - "3000:3000"
    links:
      - db
  
  nginx:
    # docker-compose buildのときにビルドするためのDockerfileのパス
    build: 
      context: ./nginx
    ports:
      - 80:80
    depends_on:
      - web
    volumes:
      - public-data:/cocktail/public
      - tmp-data:/cocktailApp/tmp
volumes:
  public-data:
  tmp-data:
  log-data: